#include <string>

static const std::string createEquitiesSql = 
    "CREATE TABLE IF NOT EXISTS EQUITIES "
    "("
        "NAME               TEXT,"
        "ISIN               TEXT,"
        "SYMBOL             TEXT,"
        "MARKET             TEXT,"
        "TRADING_CURRENCY   TEXT,"
        "OPEN               REAL,"
        "HIGH               REAL,"
        "LOW                REAL,"
        "LAST               REAL,"
        "LAST_DATETIME      TEXT,"
        "TIMEZONE           TEXT,"
        "VOLUME             INTEGER,"
        "TURNOVER           REAL"
    ");";
    
static const std::string createBondsSql =
    "CREATE TABLE IF NOT EXISTS BONDS "
    "("
        "NAME                TEXT,"
        "ISIN                TEXT,"
        "SYMBOL              TEXT,"
        "LOCATION            TEXT,"
        "MATURITY            TEXT,"
        "TRADING_CURRENCY    TEXT,"
        "OPEN                REAL,"
        "HIGH                REAL,"
        "LOW                 REAL,"
        "LAST                REAL,"
        "LAST_DATETIME       TEXT,"
        "TIMEZONE            TEXT,"
        "VOLUME              INTEGER,"
        "TURNOVER            REAL"
    ");";

static const std::string createIndicesSql =
    "CREATE TABLE IF NOT EXISTS INDICES "
    "("
        "NAME                TEXT,"
        "ISIN                TEXT,"
        "SYMBOL              TEXT,"
        "TRADING_CURRENCY    TEXT,"
        "OPEN                REAL,"
        "HIGH                REAL,"
        "LOW                 REAL,"
        "LAST                REAL,"
        "LAST_DATETIME       TEXT,"
        "TIMEZONE            TEXT"
    ");";

static const std::string createETFSSql =
    "CREATE TABLE IF NOT EXISTS ETFS "
    "("
        "NAME                TEXT,"
        "ISIN                TEXT,"
        "SYMBOL              TEXT,"
        "LOCATION            TEXT,"
        "TRADING_CURRENCY    TEXT,"
        "OPEN                REAL,"
        "HIGH                REAL,"
        "LOW                 REAL,"
        "LAST                REAL,"
        "LAST_DATETIME       TEXT,"
        "TIMEZONE            TEXT,"
        "VOLUME              INTEGER,"
        "TURNOVER            REAL"
    ");";
    
static const std::string createStructProdsSql =
    "CREATE TABLE IF NOT EXISTS STRUCT_PRODS "
    "("
        "NAME                TEXT,"
        "ISIN                TEXT,"
        "SYMBOL              TEXT,"
        "LOCATION            TEXT,"
        "C_P                 TEXT,"
        "STRIKE              REAL,"
        "MATURITY            TEXT,"
        "TRADING_CURRENCY    TEXT,"
        "OPEN                REAL,"
        "HIGH                REAL,"
        "LOW                 REAL,"
        "LAST                REAL,"
        "LAST_DATETIME       TEXT,"
        "TIMEZONE            TEXT,"
        "VOLUME              INTEGER,"
        "TURNOVER            REAL"
    ");";
